services:
  backend:
    build:
      context: .
      dockerfile: backend/src/Dockerfile
    container_name: churn-prediction-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - churn-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: churn-prediction-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://backend:8000
    networks:
      - churn-network

networks:
  churn-network:
    driver: bridge